import { useEffect, useMemo, useRef, useState } from "react";
import PropTypes from "prop-types";
import * as d3 from "d3";

// Viridis stops. Commits are coloured by time of day, so the ramp encodes
// something real rather than decorating the plot.
const VIRIDIS = ["#440154", "#3B528B", "#21918C", "#5EC962", "#FDE725"];

const PLOT_H = 300;
const MARGIN = { top: 18, right: 16, bottom: 30, left: 46 };

/**
 * The hero plot: every commit to this repo, placed by date and time of day,
 * sized by how much it changed.
 *
 * This is the thesis of the design -- the most characteristic thing in the
 * subject's world is a plot of real measurements, and the measurements are of
 * the page you are looking at.
 *
 * Reads meta/commits.csv (generated by `npm run meta` from the git log), NOT
 * meta/loc.csv. loc.csv is a per-line git blame, so it only sees commits whose
 * lines still survive and collapses to a handful after any large rewrite.
 *
 * Decorative at the SVG level; the same figures are exposed as text in the
 * hero readout, which is what assistive tech gets.
 */
const CommitScatter = ({ onStats }) => {
  const hostRef = useRef(null);
  const [commits, setCommits] = useState([]);
  const [width, setWidth] = useState(760);

  useEffect(() => {
    let cancelled = false;

    // Absolute, matching CommitGraph's existing "/meta/loc.csv". These are
    // runtime fetches from public/, not bundled assets, so Vite's base: "./"
    // does not rewrite them; the site lives at the domain root.
    d3.csv("/meta/commits.csv", (row) => {
      const datetime = new Date(row.datetime);
      return {
        hash: row.hash,
        datetime,
        hourFrac: datetime.getHours() + datetime.getMinutes() / 60,
        churn: (Number(row.insertions) || 0) + (Number(row.deletions) || 0),
        files: Number(row.files) || 0,
      };
    })
      .then((rows) => {
        if (cancelled || !rows?.length) return;
        const clean = rows
          .filter((c) => !Number.isNaN(+c.datetime))
          .sort((a, b) => a.datetime - b.datetime);

        setCommits(clean);
        onStats?.({
          commits: clean.length,
          churn: d3.sum(clean, (c) => c.churn),
          span: clean.length
            ? d3.timeYear.count(clean[0].datetime, clean.at(-1).datetime)
            : 0,
          lastCommit: clean.at(-1)?.datetime ?? null,
        });
      })
      // The plot is enhancement, not content. A missing CSV leaves the hero
      // text intact rather than blanking the page.
      .catch(() => {});

    return () => {
      cancelled = true;
    };
  }, [onStats]);

  useEffect(() => {
    const el = hostRef.current;
    if (!el) return undefined;
    const ro = new ResizeObserver(([entry]) => {
      setWidth(Math.max(280, entry.contentRect.width));
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const { points, xTicks, yTicks, innerW, innerH } = useMemo(() => {
    const iw = width - MARGIN.left - MARGIN.right;
    const ih = PLOT_H - MARGIN.top - MARGIN.bottom;
    if (!commits.length) {
      return { points: [], xTicks: [], yTicks: [], innerW: iw, innerH: ih };
    }

    // Pad by 3% of the span rather than .nice(): nice() rounds out to whole
    // months and left a wide empty band past the most recent commit.
    const [t0, t1] = d3.extent(commits, (d) => d.datetime);
    const pad = Math.max((t1 - t0) * 0.03, 36e5);
    const x = d3
      .scaleTime()
      .domain([new Date(+t0 - pad), new Date(+t1 + pad)])
      .range([0, iw]);
    const y = d3.scaleLinear().domain([24, 0]).range([ih, 0]);
    const r = d3
      .scaleSqrt()
      .domain([0, d3.max(commits, (d) => d.churn) || 1])
      .range([3.5, 17])
      .clamp(true);
    const color = d3.scaleQuantize().domain([0, 24]).range(VIRIDIS);

    return {
      innerW: iw,
      innerH: ih,
      points: commits.map((c) => ({
        key: c.hash,
        cx: x(c.datetime),
        cy: y(c.hourFrac),
        r: r(c.churn),
        fill: color(c.hourFrac),
      })),
      xTicks: x
        .ticks(Math.max(2, Math.floor(iw / 140)))
        .map((t) => ({
          key: +t,
          x: x(t),
          label: d3.timeFormat("%b %Y")(t).toUpperCase(),
        }))
        // Labels are centre-anchored and ~58px wide, so one within half that
        // of either edge gets visibly clipped.
        .filter((t) => t.x > 30 && t.x < iw - 30),
      yTicks: [0, 6, 12, 18, 24].map((h) => ({
        key: h,
        y: y(h),
        label: `${String(h).padStart(2, "0")}:00`,
      })),
    };
  }, [commits, width]);

  return (
    <div ref={hostRef} className="w-full">
      <svg
        width="100%"
        height={PLOT_H}
        viewBox={`0 0 ${width} ${PLOT_H}`}
        role="presentation"
        aria-hidden="true"
      >
        <g transform={`translate(${MARGIN.left},${MARGIN.top})`}>
          {yTicks.map((t) => (
            <g key={t.key}>
              <line
                x1={0}
                x2={innerW}
                y1={t.y}
                y2={t.y}
                stroke="rgb(var(--grid))"
                strokeOpacity={0.1}
              />
              <text
                x={-12}
                y={t.y}
                dy="0.32em"
                textAnchor="end"
                fill="rgb(var(--muted))"
                style={{
                  fontFamily: "IBM Plex Mono, ui-monospace, monospace",
                  fontSize: 9,
                  letterSpacing: "0.08em",
                }}
              >
                {t.label}
              </text>
            </g>
          ))}

          {xTicks.map((t) => (
            <text
              key={t.key}
              x={t.x}
              y={innerH + 20}
              textAnchor="middle"
              fill="rgb(var(--muted))"
              style={{
                fontFamily: "IBM Plex Mono, ui-monospace, monospace",
                fontSize: 9,
                letterSpacing: "0.12em",
              }}
            >
              {t.label}
            </text>
          ))}

          {points.map((p) => (
            <circle
              key={p.key}
              cx={p.cx}
              cy={p.cy}
              r={p.r}
              fill={p.fill}
              fillOpacity={0.55}
              stroke={p.fill}
              strokeOpacity={0.95}
              strokeWidth={1}
            />
          ))}
        </g>
      </svg>
    </div>
  );
};

CommitScatter.propTypes = {
  /** Called once with { commits, churn, span, lastCommit } after the CSV loads. */
  onStats: PropTypes.func,
};

export default CommitScatter;
