import { useEffect, useRef, useState } from "react";
import { useTheme } from "../context/ThemeContext";
import * as d3 from "d3";

const CommitGraph = () => {
  const { darkMode } = useTheme();
  const containerRef = useRef(null);
  const statsRef = useRef(null);
  const chartRef = useRef(null);
  const tooltipRef = useRef(null);
  const selectionCountRef = useRef(null);
  const languageBreakdownRef = useRef(null);
  const filesContainerRef = useRef(null);
  const scrollContainerRef = useRef(null);
  const scrollStepsRef = useRef([]);

  // State for timeline slider
  const [commitProgress, setCommitProgress] = useState(100);
  const [commitMaxTime, setCommitMaxTime] = useState(null);
  const [filteredCommits, setFilteredCommits] = useState([]);
  const [scrollMode, setScrollMode] = useState(false);

  // Global variables for scales
  const xScaleRef = useRef(null);
  const yScaleRef = useRef(null);
  const rScaleRef = useRef(null);
  const dataRef = useRef(null);
  const commitsRef = useRef(null);
  const timeScaleRef = useRef(null);

  // Handle timeline slider change
  const handleTimeSliderChange = (value) => {
    setCommitProgress(value);
    if (timeScaleRef.current && commitsRef.current) {
      const newMaxTime = timeScaleRef.current.invert(value);
      setCommitMaxTime(newMaxTime);
      const filtered = commitsRef.current.filter(
        (d) => d.datetime <= newMaxTime
      );
      setFilteredCommits(filtered);
    }
  };

  // Update tooltip content
  const updateTooltip = (d) => {
    if (!tooltipRef.current) return;

    const commitElement = tooltipRef.current.querySelector("#commit-link");
    const dateElement = tooltipRef.current.querySelector("#commit-date");
    const timeElement = tooltipRef.current.querySelector("#commit-time");
    const authorElement = tooltipRef.current.querySelector("#commit-author");
    const linesElement = tooltipRef.current.querySelector("#commit-lines");

    if (commitElement) {
      commitElement.textContent = d.id.substring(0, 7);
      commitElement.href = d.url;
    }
    if (dateElement) {
      dateElement.textContent = d.datetime?.toLocaleString("en", {
        dateStyle: "full",
      });
    }
    if (timeElement) {
      timeElement.textContent = d.datetime?.toLocaleString("en", {
        timeStyle: "short",
      });
    }
    if (authorElement) authorElement.textContent = d.author;
    if (linesElement) linesElement.textContent = `${d.totalLines} changed`;
  };

  useEffect(() => {
    const renderVisualization = async () => {
      try {
        // Clear previous content
        if (statsRef.current) statsRef.current.innerHTML = "";
        if (chartRef.current) chartRef.current.innerHTML = "";
        if (languageBreakdownRef.current)
          languageBreakdownRef.current.innerHTML = "";

        // Load data from the CSV file generated by elocuent
        const loadData = async () => {
          try {
            const data = await d3.csv("/meta/loc.csv", (row) => ({
              ...row,
              line: Number(row.line),
              depth: Number(row.depth),
              length: Number(row.length),
              date: new Date(row.date + "T00:00" + row.timezone),
              datetime: new Date(row.datetime),
            }));

            console.log("Real data loaded:", data.length, "lines");
            return data;
          } catch (error) {
            console.error("Error loading CSV data:", error);
            return [];
          }
        };

        // Process commits from data
        const processCommits = (data) => {
          return d3
            .groups(data, (d) => d.commit)
            .map(([commit, lines]) => {
              let first = lines[0];
              let { author, date, time, timezone, datetime } = first;

              const ret = {
                id: commit,
                url:
                  "https://github.com/anirudh9280/portfolio/commit/" + commit,
                author,
                date,
                time,
                timezone,
                datetime,
                hourFrac: datetime.getHours() + datetime.getMinutes() / 60,
                totalLines: lines.length,
              };

              // Store the lines array as a non-enumerable property
              Object.defineProperty(ret, "lines", {
                value: lines,
                enumerable: false,
                configurable: true,
                writable: true,
              });

              return ret;
            });
        };

        // Render commit information
        const renderCommitInfo = (data, filteredCommits) => {
          // Remove any existing content
          d3.select(statsRef.current).html("");

          // Create a flex container for horizontal layout
          const container = d3
            .select(statsRef.current)
            .append("div")
            .attr("class", "flex flex-wrap justify-around gap-4");

          // Function to add a stat block
          const addStat = (title, value) => {
            const statBlock = container
              .append("div")
              .attr("class", "stat-block text-center");

            statBlock
              .append("div")
              .attr("class", "stat-title text-sm opacity-75")
              .html(title);

            statBlock
              .append("div")
              .attr("class", "stat-value text-2xl font-bold")
              .text(value);
          };

          // Add total LOC
          addStat('Total <abbr title="Lines of code">LOC</abbr>', data.length);

          // Add total commits
          addStat("Total Commits", filteredCommits.length);

          // Add number of files
          const fileCount = d3.group(data, (d) => d.file).size;
          addStat("Number of Files", fileCount);

          // Add average file length
          const fileLengths = d3.rollups(
            data,
            (v) => d3.max(v, (d) => d.line),
            (d) => d.file
          );
          const avgFileLength = Math.round(d3.mean(fileLengths, (d) => d[1]));
          addStat("Avg. File Length", avgFileLength + " lines");

          // Add longest file
          const longestFile = d3.greatest(fileLengths, (d) => d[1]);
          const shortFileName = longestFile[0].split("/").pop();
          addStat("Longest File", `${shortFileName} (${longestFile[1]} lines)`);
        };

        // Check if commit is within selection bounds
        const isCommitSelected = (selection, commit) => {
          if (!selection || !xScaleRef.current || !yScaleRef.current)
            return false;

          const x = xScaleRef.current(commit.datetime);
          const y = yScaleRef.current(commit.hourFrac);

          return (
            x >= selection[0][0] &&
            x <= selection[1][0] &&
            y >= selection[0][1] &&
            y <= selection[1][1]
          );
        };

        // Brush event handler
        const brushed = (event) => {
          const selection = event.selection;

          // Reset all circles to original color and opacity
          d3.selectAll(".commit-circle")
            .classed("selected", false)
            .attr("fill", darkMode ? "#ffffff" : "#374151") // Single color for all dots
            .style("fill-opacity", 0.7);

          // If there's a selection, highlight the selected circles
          if (selection) {
            // First filter the commits to find those that are selected
            const selectedCommits = commitsRef.current.filter((d) =>
              isCommitSelected(selection, d)
            );

            // Update the count display
            if (selectionCountRef.current) {
              selectionCountRef.current.textContent = `${selectedCommits.length || "No"} commits selected`;
            }

            // Only proceed if we have commits selected
            if (selectedCommits.length > 0) {
              // Highlight selected commits
              d3.selectAll(".commit-circle")
                .filter((d) => isCommitSelected(selection, d))
                .classed("selected", true)
                .attr("fill", "#ff6b6b") // Red for selected
                .style("fill-opacity", 1);

              // Generate language breakdown for selected commits
              if (languageBreakdownRef.current) {
                languageBreakdownRef.current.innerHTML = "";

                // Get all lines from selected commits
                const allSelectedLines = selectedCommits.flatMap(
                  (commit) => commit.lines
                );

                // Create language breakdown
                const languageBreakdown = d3.rollup(
                  allSelectedLines,
                  (v) => v.length,
                  (d) => d.type || "unknown"
                );

                // Convert to array and sort by count
                const filteredBreakdown = Array.from(
                  languageBreakdown.entries()
                )
                  .filter(([language]) => language && language !== "")
                  .sort(([, a], [, b]) => b - a);

                if (filteredBreakdown.length > 0) {
                  // Create container for horizontal display
                  const container = document.createElement("div");
                  container.className =
                    "language-breakdown-container flex flex-wrap gap-4 mt-2 justify-start";
                  languageBreakdownRef.current.appendChild(container);

                  // Add header as first item
                  const header = document.createElement("div");
                  header.className =
                    "language-breakdown-header self-center mr-2";
                  header.textContent = "Language Breakdown:";
                  container.appendChild(header);

                  // Calculate total for percentage
                  const totalLines = filteredBreakdown.reduce(
                    (sum, [, count]) => sum + count,
                    0
                  );

                  // Add each language as a horizontal item
                  filteredBreakdown.forEach(([language, count]) => {
                    const proportion = count / totalLines;
                    const formatted = d3.format(".1~%")(proportion);

                    const item = document.createElement("div");
                    item.className =
                      "language-item px-3 py-2 rounded-lg " +
                      (darkMode ? "bg-gray-700" : "bg-gray-100");

                    const langName = document.createElement("span");
                    langName.className = "font-medium";
                    langName.textContent = String(language).toUpperCase();

                    const langStats = document.createElement("span");
                    langStats.className = "ml-2 opacity-80";
                    langStats.textContent = `${count} (${formatted})`;

                    item.appendChild(langName);
                    item.appendChild(langStats);
                    container.appendChild(item);
                  });
                }
              }
            }
          } else {
            // No selection - reset count and clear language breakdown
            if (selectionCountRef.current) {
              selectionCountRef.current.textContent = "No commits selected";
            }
            if (languageBreakdownRef.current) {
              languageBreakdownRef.current.innerHTML = "";
            }
          }
        };

        // Load and process data
        const data = await loadData();
        dataRef.current = data;

        if (data.length === 0) {
          if (statsRef.current) {
            statsRef.current.innerHTML = `
              <div class="text-center p-8">
                <p class="text-lg ${darkMode ? "text-white" : "text-gray-800"}">No commit data available</p>
                <p class="text-sm ${darkMode ? "text-gray-400" : "text-gray-600"} mt-2">Unable to load repository commit history</p>
              </div>
            `;
          }
          return;
        }

        const commits = processCommits(data);
        commitsRef.current = commits;

        // Create time scale for the slider
        const [minDate, maxDate] = d3.extent(commits, (d) => d.datetime);
        timeScaleRef.current = d3
          .scaleTime()
          .domain([minDate, maxDate])
          .range([0, 100]);

        // Initialize filtered commits and max time
        if (!commitMaxTime) {
          setCommitMaxTime(maxDate);
          setFilteredCommits(commits);
        }

        // Render basic stats
        renderCommitInfo(data, filteredCommits);

        // Set up visualization dimensions
        const margin = { top: 60, right: 120, bottom: 80, left: 80 };
        const width = Math.max(800, containerRef.current?.clientWidth || 800);
        const height = 500;

        const usableArea = {
          left: margin.left,
          right: width - margin.right,
          top: margin.top,
          bottom: height - margin.bottom,
          width: width - margin.left - margin.right,
          height: height - margin.top - margin.bottom,
        };

        // Clear and create SVG
        d3.select(chartRef.current).selectAll("*").remove();
        const svg = d3
          .select(chartRef.current)
          .append("svg")
          .attr("width", width)
          .attr("height", height);

        // Set up scales
        xScaleRef.current = d3
          .scaleTime()
          .domain([minDate, maxDate])
          .range([usableArea.left, usableArea.right])
          .nice();

        yScaleRef.current = d3
          .scaleLinear()
          .domain([0, 24])
          .range([usableArea.bottom, usableArea.top]);

        const [minLines, maxLines] = d3.extent(commits, (d) => d.totalLines);
        rScaleRef.current = d3
          .scaleSqrt()
          .domain([minLines, maxLines])
          .range([3, 15]);

        // Create brush
        const brush = d3
          .brush()
          .extent([
            [usableArea.left, usableArea.top],
            [usableArea.right, usableArea.bottom],
          ])
          .on("brush end", brushed);

        // Add brush to SVG
        svg.append("g").attr("class", "brush").call(brush);

        // Add gridlines
        const gridlines = svg
          .append("g")
          .attr("class", "gridlines")
          .attr("transform", `translate(${usableArea.left}, 0)`);

        gridlines.call(
          d3
            .axisLeft(yScaleRef.current)
            .tickFormat("")
            .tickSize(-usableArea.width)
            .tickValues(d3.range(0, 25, 4)) // Every 4 hours
        );

        // Add axes
        const xAxis = d3
          .axisBottom(xScaleRef.current)
          .tickFormat(d3.timeFormat("%b %d"));
        const yAxis = d3.axisLeft(yScaleRef.current).tickFormat((d) => {
          if (d === 0) return "12 AM";
          if (d === 12) return "12 PM";
          if (d < 12) return `${d} AM`;
          return `${d - 12} PM`;
        });

        // Add X axis
        svg
          .append("g")
          .attr("class", "x-axis")
          .attr("transform", `translate(0, ${usableArea.bottom})`)
          .call(xAxis)
          .append("text")
          .attr("x", usableArea.left + usableArea.width / 2)
          .attr("y", 40)
          .attr("fill", darkMode ? "#e5e7eb" : "currentColor")
          .attr("text-anchor", "middle")
          .text("Date");

        // Add Y axis
        svg
          .append("g")
          .attr("class", "y-axis")
          .attr("transform", `translate(${usableArea.left}, 0)`)
          .call(yAxis)
          .append("text")
          .attr("transform", "rotate(-90)")
          .attr("x", -usableArea.top - usableArea.height / 2)
          .attr("y", -40)
          .attr("fill", darkMode ? "#e5e7eb" : "currentColor")
          .attr("text-anchor", "middle")
          .text("Time of Day");

        // Sort commits by size for better visibility
        const sortedCommits = d3.sort(filteredCommits, (d) => -d.totalLines);

        // Add circles for commits
        svg
          .selectAll(".commit-circle")
          .data(sortedCommits, (d) => d.id) // Add key function for stable transitions
          .enter()
          .append("circle")
          .attr("class", "commit-circle")
          .attr("cx", (d) => xScaleRef.current(d.datetime))
          .attr("cy", (d) => yScaleRef.current(d.hourFrac))
          .attr("r", (d) => rScaleRef.current(d.totalLines))
          .attr("fill", darkMode ? "#ffffff" : "#374151") // Single color for all dots
          .style("fill-opacity", 0.7)
          .style("stroke", darkMode ? "#6b7280" : "#9ca3af")
          .style("stroke-width", 1)
          .style("cursor", "pointer")
          .on("mouseover", function (event, d) {
            // Show tooltip
            if (tooltipRef.current) {
              updateTooltip(d);
              tooltipRef.current.hidden = false;
              const tooltip = d3.select(tooltipRef.current);
              tooltip
                .style("left", event.pageX + 10 + "px")
                .style("top", event.pageY - 10 + "px");
            }

            // Highlight circle
            d3.select(this).style("fill-opacity", 1).style("stroke-width", 2);
          })
          .on("mousemove", function (event) {
            if (tooltipRef.current) {
              const tooltip = d3.select(tooltipRef.current);
              tooltip
                .style("left", event.pageX + 10 + "px")
                .style("top", event.pageY - 10 + "px");
            }
          })
          .on("mouseout", function () {
            // Hide tooltip
            if (tooltipRef.current) {
              tooltipRef.current.hidden = true;
            }

            // Reset circle appearance (unless it's selected)
            if (!d3.select(this).classed("selected")) {
              d3.select(this)
                .style("fill-opacity", 0.7)
                .style("stroke-width", 1);
            }
          })
          .on("click", function (event, d) {
            window.open(d.url, "_blank");
          });

        // Raise dots above the brush overlay
        svg.selectAll(".commit-circle").raise();
      } catch (error) {
        console.error("Error in renderVisualization:", error);
        if (statsRef.current) {
          statsRef.current.innerHTML = `
            <div class="text-center p-8">
              <p class="text-lg ${darkMode ? "text-white" : "text-gray-800"}">Error loading visualization</p>
              <p class="text-sm ${darkMode ? "text-gray-400" : "text-gray-600"} mt-2">${error.message}</p>
            </div>
          `;
        }
      }
    };

    renderVisualization();

    // Add custom styles
    const newStyle = document.createElement("style");
    newStyle.textContent = `
      .commit-graph-container .tooltip {
        position: absolute;
        background: ${darkMode ? "rgba(31, 41, 55, 0.95)" : "rgba(255, 255, 255, 0.95)"};
        border: 1px solid ${darkMode ? "#4b5563" : "#d1d5db"};
        border-radius: 8px;
        padding: 12px;
        font-size: 14px;
        pointer-events: none;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        z-index: 1000;
        color: ${darkMode ? "#f3f4f6" : "#1f2937"};
      }
      
      .commit-graph-container .tooltip dt {
        font-weight: 600;
        margin-top: 0.5rem;
        color: ${darkMode ? "#e5e7eb" : "#374151"};
      }
      
      .commit-graph-container .tooltip dt:first-child {
        margin-top: 0;
      }
      
      .commit-graph-container .tooltip dd {
        margin-left: 0;
        margin-bottom: 0.25rem;
        color: ${darkMode ? "#d1d5db" : "#6b7280"};
      }
      
      .commit-graph-container .tooltip a {
        color: ${darkMode ? "#60a5fa" : "#3b82f6"};
        text-decoration: underline;
      }
      
      .commit-graph-container .language-breakdown-container {
        display: flex;
        flex-wrap: wrap;
        gap: 1rem;
        margin-top: 0.5rem;
        justify-content: flex-start;
        align-items: center;
      }
      
      .commit-graph-container .language-breakdown-header {
        font-weight: 600;
        color: ${darkMode ? "#e5e7eb" : "#374151"};
        margin-right: 0.5rem;
        align-self: center;
      }
      
      .commit-graph-container .language-item {
        padding: 0.5rem 0.75rem;
        border-radius: 0.5rem;
        background-color: ${darkMode ? "rgba(55, 65, 81, 0.7)" : "rgba(243, 244, 246, 0.7)"};
        font-size: 0.9rem;
        line-height: 1.2;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      
      .commit-graph-container .language-item span {
        display: block;
      }

      .commit-graph-container .gridlines line {
        stroke: ${darkMode ? "#4b5563" : "#d1d5db"};
        stroke-opacity: 0.5;
      }

      .commit-graph-container .gridlines path {
        display: none;
      }

      .commit-graph-container .brush .selection {
        fill-opacity: 0.1;
        stroke: ${darkMode ? "#60a5fa" : "#3b82f6"};
        stroke-opacity: 0.7;
        stroke-dasharray: 5 3;
      }

      .commit-graph-container circle.selected {
        stroke: #ff6b6b;
        stroke-width: 2px;
      }

      /* Timeline slider styling */
      .commit-graph-container input[type="range"] {
        -webkit-appearance: none;
        appearance: none;
        height: 6px;
        background: ${darkMode ? "#4b5563" : "#d1d5db"};
        border-radius: 3px;
        outline: none;
        transition: opacity 0.2s;
      }

      .commit-graph-container input[type="range"]::-webkit-slider-thumb {
        -webkit-appearance: none;
        appearance: none;
        width: 18px;
        height: 18px;
        background: ${darkMode ? "#60a5fa" : "#3b82f6"};
        border-radius: 50%;
        cursor: pointer;
        transition: all 0.2s ease;
      }

      .commit-graph-container input[type="range"]::-webkit-slider-thumb:hover {
        transform: scale(1.2);
        box-shadow: 0 0 0 8px ${darkMode ? "rgba(96, 165, 250, 0.1)" : "rgba(59, 130, 246, 0.1)"};
      }

      .commit-graph-container input[type="range"]::-moz-range-thumb {
        width: 18px;
        height: 18px;
        background: ${darkMode ? "#60a5fa" : "#3b82f6"};
        border-radius: 50%;
        cursor: pointer;
        border: none;
        transition: all 0.2s ease;
      }

      .commit-graph-container input[type="range"]::-moz-range-thumb:hover {
        transform: scale(1.2);
        box-shadow: 0 0 0 8px ${darkMode ? "rgba(96, 165, 250, 0.1)" : "rgba(59, 130, 246, 0.1)"};
      }

      /* Entry animation for circles */
      @starting-style {
        .commit-circle {
          r: 0;
        }
      }

      .commit-circle {
        transition: all 200ms, r calc(var(--r) * 50ms);
      }
    `;
    document.head.appendChild(newStyle);

    return () => {
      if (newStyle && newStyle.parentNode) {
        newStyle.parentNode.removeChild(newStyle);
      }
    };
  }, [darkMode]);

  // Update visualization when filtered commits change
  useEffect(() => {
    if (filteredCommits.length === 0 || !dataRef.current || !xScaleRef.current)
      return;

    // Update stats
    const renderCommitInfo = (data, filteredCommits) => {
      d3.select(statsRef.current).html("");

      const container = d3
        .select(statsRef.current)
        .append("div")
        .attr("class", "flex flex-wrap justify-around gap-4");

      const addStat = (title, value) => {
        const statBlock = container
          .append("div")
          .attr("class", "stat-block text-center");

        statBlock
          .append("div")
          .attr("class", "stat-title text-sm opacity-75")
          .html(title);

        statBlock
          .append("div")
          .attr("class", "stat-value text-2xl font-bold")
          .text(value);
      };

      addStat('Total <abbr title="Lines of code">LOC</abbr>', data.length);
      addStat("Total Commits", filteredCommits.length);

      const fileCount = d3.group(data, (d) => d.file).size;
      addStat("Number of Files", fileCount);

      const fileLengths = d3.rollups(
        data,
        (v) => d3.max(v, (d) => d.line),
        (d) => d.file
      );
      const avgFileLength = Math.round(d3.mean(fileLengths, (d) => d[1]));
      addStat("Avg. File Length", avgFileLength + " lines");

      const longestFile = d3.greatest(fileLengths, (d) => d[1]);
      const shortFileName = longestFile[0].split("/").pop();
      addStat("Longest File", `${shortFileName} (${longestFile[1]} lines)`);
    };

    renderCommitInfo(dataRef.current, filteredCommits);

    // Update scatter plot
    const svg = d3.select(chartRef.current).select("svg");
    if (!svg.node()) return;

    // Update x-axis domain
    const [minDate, maxDate] = d3.extent(filteredCommits, (d) => d.datetime);
    xScaleRef.current.domain([minDate, maxDate]);

    // Update x-axis
    const xAxis = d3
      .axisBottom(xScaleRef.current)
      .tickFormat(d3.timeFormat("%b %d"));
    svg.select(".x-axis").transition().duration(500).call(xAxis);

    // Update radius scale
    const [minLines, maxLines] = d3.extent(
      filteredCommits,
      (d) => d.totalLines
    );
    const rScale = d3.scaleSqrt().domain([minLines, maxLines]).range([3, 15]);

    // Sort commits by size
    const sortedCommits = d3.sort(filteredCommits, (d) => -d.totalLines);

    // Update circles with transitions
    svg
      .selectAll(".commit-circle")
      .data(sortedCommits, (d) => d.id)
      .join(
        (enter) =>
          enter
            .append("circle")
            .attr("class", "commit-circle")
            .attr("cx", (d) => xScaleRef.current(d.datetime))
            .attr("cy", (d) => yScaleRef.current(d.hourFrac))
            .attr("r", 0)
            .attr("fill", darkMode ? "#ffffff" : "#374151")
            .style("fill-opacity", 0.7)
            .style("stroke", darkMode ? "#6b7280" : "#9ca3af")
            .style("stroke-width", 1)
            .style("cursor", "pointer")
            .call((enter) =>
              enter
                .transition()
                .duration(500)
                .attr("r", (d) => rScale(d.totalLines))
            ),
        (update) =>
          update
            .transition()
            .duration(500)
            .attr("cx", (d) => xScaleRef.current(d.datetime))
            .attr("r", (d) => rScale(d.totalLines)),
        (exit) => exit.transition().duration(500).attr("r", 0).remove()
      )
      .on("mouseover", function (event, d) {
        if (tooltipRef.current) {
          updateTooltip(d);
          tooltipRef.current.hidden = false;
          const tooltip = d3.select(tooltipRef.current);
          tooltip
            .style("left", event.pageX + 10 + "px")
            .style("top", event.pageY - 10 + "px");
        }
        d3.select(this).style("fill-opacity", 1).style("stroke-width", 2);
      })
      .on("mousemove", function (event) {
        if (tooltipRef.current) {
          const tooltip = d3.select(tooltipRef.current);
          tooltip
            .style("left", event.pageX + 10 + "px")
            .style("top", event.pageY - 10 + "px");
        }
      })
      .on("mouseout", function () {
        if (tooltipRef.current) {
          tooltipRef.current.hidden = true;
        }
        if (!d3.select(this).classed("selected")) {
          d3.select(this).style("fill-opacity", 0.7).style("stroke-width", 1);
        }
      })
      .on("click", function (event, d) {
        window.open(d.url, "_blank");
      });

    // Ensure dots are above brush
    svg.selectAll(".commit-circle").raise();

    // Update file visualization
    if (filesContainerRef.current) {
      const lines = filteredCommits.flatMap((d) => d.lines);
      const files = d3
        .groups(lines, (d) => d.file)
        .map(([name, lines]) => ({ name, lines }))
        .sort((a, b) => b.lines.length - a.lines.length);

      // Create ordinal color scale for file types
      const colors = d3.scaleOrdinal(d3.schemeTableau10);

      // Update file display
      const filesContainer = d3
        .select(filesContainerRef.current)
        .selectAll("div.file-item")
        .data(files, (d) => d.name)
        .join(
          (enter) =>
            enter
              .append("div")
              .attr("class", "file-item grid grid-cols-[1fr,3fr] gap-4 mb-4")
              .call((div) => {
                div
                  .append("div")
                  .attr("class", "file-info")
                  .call((info) => {
                    info
                      .append("code")
                      .attr("class", "block text-sm font-mono break-all");
                    info
                      .append("small")
                      .attr("class", "block text-xs opacity-60 mt-1");
                  });
                div
                  .append("div")
                  .attr(
                    "class",
                    "file-lines flex flex-wrap gap-[0.15em] items-start"
                  );
              }),
          (update) => update,
          (exit) => exit.remove()
        );

      // Update file names and line counts
      filesContainer.select(".file-info code").text((d) => d.name);
      filesContainer
        .select(".file-info small")
        .text((d) => `${d.lines.length} lines`);

      // Update dots for each line
      filesContainer.each(function (fileData) {
        d3.select(this)
          .select(".file-lines")
          .selectAll("div.loc")
          .data(fileData.lines)
          .join("div")
          .attr("class", "loc")
          .style("width", "0.5em")
          .style("height", "0.5em")
          .style("background", (d) => colors(d.type || "unknown"))
          .style("border-radius", "50%");
      });
    }
  }, [filteredCommits, darkMode]);

  // Set up scrollytelling with Intersection Observer
  useEffect(() => {
    if (!scrollMode || !commitsRef.current || !timeScaleRef.current) return;

    const observerOptions = {
      root: null,
      rootMargin: "-50% 0px",
      threshold: 0,
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          const commitData = entry.target.__commitData;
          if (commitData) {
            // Update progress based on the commit's datetime
            const progress = timeScaleRef.current(commitData.datetime);
            setCommitProgress(progress);
            handleTimeSliderChange(progress);
          }
        }
      });
    }, observerOptions);

    // Observe all scroll steps
    scrollStepsRef.current.forEach((step) => {
      if (step) observer.observe(step);
    });

    return () => {
      scrollStepsRef.current.forEach((step) => {
        if (step) observer.unobserve(step);
      });
    };
  }, [scrollMode, commitsRef.current]);

  return (
    <div
      className={`w-full mt-16 mb-16 ${
        darkMode ? "text-white" : "text-gray-800"
      }`}
      ref={containerRef}
    >
      <div className="commit-graph-container">
        <h2 className={`text-center text-3xl font-bold mb-2`}>
          Portfolio Development Activity
        </h2>
        <p className="text-center text-lg mb-8">
          Tracking commits and development patterns for this personal portfolio
        </p>

        {/* Timeline slider */}
        {commitMaxTime && (
          <div
            className={`p-4 rounded-lg mb-4 flex items-baseline gap-4 ${
              darkMode
                ? "bg-gray-800/80 border border-gray-700"
                : "bg-white/80 border border-gray-200"
            }`}
          >
            <label className="flex-1 flex items-baseline gap-4">
              <span>Show commits until:</span>
              <input
                type="range"
                min="0"
                max="100"
                value={commitProgress}
                onChange={(e) => handleTimeSliderChange(e.target.value)}
                className="flex-1"
                id="commit-progress"
              />
              <time className="ml-auto font-mono">
                {commitMaxTime.toLocaleString("en", {
                  dateStyle: "long",
                  timeStyle: "short",
                })}
              </time>
            </label>
          </div>
        )}

        {/* Stats bar - horizontal instead of vertical */}
        <div
          ref={statsRef}
          className={`p-6 rounded-lg mb-8 ${
            darkMode
              ? "bg-gray-800/80 border border-gray-700"
              : "bg-white/80 border border-gray-200"
          }`}
        ></div>

        {/* Main chart section - now full width */}
        <div
          className={`p-6 rounded-lg ${
            darkMode
              ? "bg-gray-800/80 border border-gray-700"
              : "bg-white/80 border border-gray-200"
          }`}
        >
          <h3 className="text-xl font-semibold mb-4">Commits by Time of Day</h3>
          <p className="mb-4 opacity-75">
            Drag to select commits and see language breakdown. Click dots to
            view commits on GitHub.
          </p>
          <div ref={chartRef}></div>

          <dl ref={tooltipRef} className="tooltip" hidden>
            <dt>Commit</dt>
            <dd>
              <a href="" id="commit-link" target="_blank" rel="noreferrer"></a>
            </dd>
            <dt>Date</dt>
            <dd id="commit-date"></dd>
            <dt>Time</dt>
            <dd id="commit-time"></dd>
            <dt>Author</dt>
            <dd id="commit-author"></dd>
            <dt>Lines</dt>
            <dd id="commit-lines"></dd>
          </dl>

          <div className="selection-info mt-4">
            <p ref={selectionCountRef} id="selection-count">
              No commits selected
            </p>
            <dl ref={languageBreakdownRef} className="stats mt-2"></dl>
          </div>
        </div>

        {/* File visualization section */}
        {filteredCommits.length > 0 && (
          <div
            className={`p-6 rounded-lg mt-8 ${
              darkMode
                ? "bg-gray-800/80 border border-gray-700"
                : "bg-white/80 border border-gray-200"
            }`}
          >
            <h3 className="text-xl font-semibold mb-4">
              The Race for the Biggest File!
            </h3>
            <p className="mb-6 opacity-75">
              File sizes over time, colored by technology. Each dot represents
              one line of code.
            </p>
            <div
              ref={filesContainerRef}
              className="max-h-96 overflow-y-auto"
            ></div>
          </div>
        )}

        {/* Scrollytelling section */}
        <div className="mt-8">
          <div className="text-center mb-6">
            <button
              onClick={() => setScrollMode(!scrollMode)}
              className={`px-6 py-3 rounded-lg font-medium transition-all ${
                darkMode
                  ? "bg-blue-600 hover:bg-blue-700 text-white"
                  : "bg-blue-500 hover:bg-blue-600 text-white"
              }`}
            >
              {scrollMode ? "Exit Story Mode" : "Enter Story Mode"}
            </button>
            {scrollMode && (
              <p className="mt-2 text-sm opacity-75">
                Scroll down to see how the repository evolved over time
              </p>
            )}
          </div>

          {scrollMode && (
            <div className="relative flex gap-8 mt-12" ref={scrollContainerRef}>
              {/* Story content on the left */}
              <div className="flex-1 space-y-[50vh]">
                {commitsRef.current &&
                  commitsRef.current.map((commit, i) => (
                    <div
                      key={commit.id}
                      ref={(el) => {
                        scrollStepsRef.current[i] = el;
                        if (el) el.__commitData = commit;
                      }}
                      className={`p-6 rounded-lg ${
                        darkMode
                          ? "bg-gray-800/80 border border-gray-700"
                          : "bg-white/80 border border-gray-200"
                      }`}
                    >
                      <p className="text-lg">
                        On{" "}
                        <time className="font-medium">
                          {commit.datetime.toLocaleString("en", {
                            dateStyle: "full",
                            timeStyle: "short",
                          })}
                        </time>
                        , I made{" "}
                        <a
                          href={commit.url}
                          target="_blank"
                          rel="noreferrer"
                          className={`underline ${
                            darkMode ? "text-blue-400" : "text-blue-600"
                          }`}
                        >
                          {i > 0
                            ? "another glorious commit"
                            : "my first commit, and it was glorious"}
                        </a>
                        . I edited{" "}
                        <span className="font-bold">
                          {commit.totalLines} lines
                        </span>{" "}
                        across{" "}
                        <span className="font-bold">
                          {
                            d3.rollups(
                              commit.lines,
                              (D) => D.length,
                              (d) => d.file
                            ).length
                          }{" "}
                          files
                        </span>
                        . Then I looked over all I had made, and I saw that it
                        was very good.
                      </p>
                    </div>
                  ))}
              </div>

              {/* Fixed visualization on the right */}
              <div className="flex-1 sticky top-20 h-[80vh]">
                <div
                  className={`h-full p-4 rounded-lg overflow-hidden ${
                    darkMode
                      ? "bg-gray-800/80 border border-gray-700"
                      : "bg-white/80 border border-gray-200"
                  }`}
                >
                  <h4 className="text-lg font-medium mb-2">
                    Repository at this point:
                  </h4>
                  <div className="text-sm opacity-75 mb-4">
                    {filteredCommits.length} commits •{" "}
                    {filteredCommits.flatMap((c) => c.lines).length} lines
                    changed
                  </div>

                  {/* File visualization */}
                  <div className="overflow-y-auto h-[calc(100%-5rem)]">
                    {(() => {
                      const lines = filteredCommits.flatMap((d) => d.lines);
                      const files = d3
                        .groups(lines, (d) => d.file)
                        .map(([name, lines]) => ({ name, lines }))
                        .sort((a, b) => b.lines.length - a.lines.length);

                      const colors = d3.scaleOrdinal(d3.schemeTableau10);

                      return files.map((file) => (
                        <div
                          key={file.name}
                          className="grid grid-cols-[1fr,3fr] gap-4 mb-4"
                        >
                          <div className="file-info">
                            <code className="block text-xs font-mono break-all">
                              {file.name}
                            </code>
                            <small className="block text-xs opacity-60 mt-1">
                              {file.lines.length} lines
                            </small>
                          </div>
                          <div className="file-lines flex flex-wrap gap-[0.15em] items-start">
                            {file.lines.map((line, i) => (
                              <div
                                key={`${file.name}-${i}`}
                                className="loc"
                                style={{
                                  width: "0.5em",
                                  height: "0.5em",
                                  background: colors(line.type || "unknown"),
                                  borderRadius: "50%",
                                }}
                              />
                            ))}
                          </div>
                        </div>
                      ));
                    })()}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CommitGraph;
