import React, { useEffect, useRef } from "react";
import { useTheme } from "../context/ThemeContext";
import * as d3 from "d3";

const CommitGraph = () => {
  const { darkMode } = useTheme();
  const containerRef = useRef(null);
  const statsRef = useRef(null);
  const chartRef = useRef(null);
  const tooltipRef = useRef(null);
  const selectionCountRef = useRef(null);
  const languageBreakdownRef = useRef(null);

  // Global variables for scales
  let xScale, yScale, rScale;
  let dataRef = useRef(null);
  let commitsRef = useRef(null);

  useEffect(() => {
    const renderVisualization = async () => {
      try {
        // Clear previous content
        if (statsRef.current) statsRef.current.innerHTML = "";
        if (chartRef.current) chartRef.current.innerHTML = "";
        if (languageBreakdownRef.current)
          languageBreakdownRef.current.innerHTML = "";

        // Load data from the CSV file generated by elocuent
        const loadData = async () => {
          try {
            const data = await d3.csv("/meta/loc.csv", (row) => ({
              ...row,
              line: Number(row.line),
              depth: Number(row.depth),
              length: Number(row.length),
              date: new Date(row.date + "T00:00" + row.timezone),
              datetime: new Date(row.datetime),
            }));

            console.log("Real data loaded:", data.length, "lines");
            return data;
          } catch (error) {
            console.error("Error loading CSV data:", error);
            return [];
          }
        };

        // Process commits from data
        const processCommits = (data) => {
          return d3
            .groups(data, (d) => d.commit)
            .map(([commit, lines]) => {
              let first = lines[0];
              let { author, date, time, timezone, datetime } = first;

              const ret = {
                id: commit,
                url:
                  "https://github.com/anirudh9280/portfolio/commit/" + commit,
                author,
                date,
                time,
                timezone,
                datetime,
                hourFrac: datetime.getHours() + datetime.getMinutes() / 60,
                totalLines: lines.length,
              };

              // Store the lines array as a non-enumerable property
              Object.defineProperty(ret, "lines", {
                value: lines,
                enumerable: false,
                configurable: true,
                writable: true,
              });

              return ret;
            });
        };

        // Render commit information
        const renderCommitInfo = (data, commits) => {
          // Remove any existing content
          d3.select(statsRef.current).html("");

          // Create a flex container for horizontal layout
          const container = d3
            .select(statsRef.current)
            .append("div")
            .attr("class", "flex flex-wrap justify-around gap-4");

          // Function to add a stat block
          const addStat = (title, value) => {
            const statBlock = container
              .append("div")
              .attr("class", "stat-block text-center");

            statBlock
              .append("div")
              .attr("class", "stat-title text-sm opacity-75")
              .html(title);

            statBlock
              .append("div")
              .attr("class", "stat-value text-2xl font-bold")
              .text(value);
          };

          // Add total LOC
          addStat('Total <abbr title="Lines of code">LOC</abbr>', data.length);

          // Add total commits
          addStat("Total Commits", commits.length);

          // Add number of files
          const fileCount = d3.group(data, (d) => d.file).size;
          addStat("Number of Files", fileCount);

          // Add average file length
          const fileLengths = d3.rollups(
            data,
            (v) => d3.max(v, (d) => d.line),
            (d) => d.file
          );
          const avgFileLength = Math.round(d3.mean(fileLengths, (d) => d[1]));
          addStat("Avg. File Length", avgFileLength + " lines");

          // Add longest file
          const longestFile = d3.greatest(fileLengths, (d) => d[1]);
          const shortFileName = longestFile[0].split("/").pop();
          addStat("Longest File", `${shortFileName} (${longestFile[1]} lines)`);
        };

        // Update tooltip content
        const updateTooltip = (d) => {
          if (!tooltipRef.current) return;

          const commitElement =
            tooltipRef.current.querySelector("#commit-link");
          const dateElement = tooltipRef.current.querySelector("#commit-date");
          const timeElement = tooltipRef.current.querySelector("#commit-time");
          const authorElement =
            tooltipRef.current.querySelector("#commit-author");
          const linesElement =
            tooltipRef.current.querySelector("#commit-lines");

          if (commitElement) {
            commitElement.textContent = d.id.substring(0, 7);
            commitElement.href = d.url;
          }
          if (dateElement) {
            dateElement.textContent = d.datetime?.toLocaleString("en", {
              dateStyle: "full",
            });
          }
          if (timeElement) {
            timeElement.textContent = d.datetime?.toLocaleString("en", {
              timeStyle: "short",
            });
          }
          if (authorElement) authorElement.textContent = d.author;
          if (linesElement)
            linesElement.textContent = `${d.totalLines} changed`;
        };

        // Check if commit is within selection bounds
        const isCommitSelected = (selection, commit) => {
          if (!selection || !xScale || !yScale) return false;

          const x = xScale(commit.datetime);
          const y = yScale(commit.hourFrac);

          return (
            x >= selection[0][0] &&
            x <= selection[1][0] &&
            y >= selection[0][1] &&
            y <= selection[1][1]
          );
        };

        // Brush event handler
        const brushed = (event) => {
          const selection = event.selection;

          // Reset all circles to original color and opacity
          d3.selectAll(".commit-circle")
            .classed("selected", false)
            .attr("fill", darkMode ? "#ffffff" : "#374151") // Single color for all dots
            .style("fill-opacity", 0.7);

          // If there's a selection, highlight the selected circles
          if (selection) {
            // First filter the commits to find those that are selected
            const selectedCommits = commitsRef.current.filter((d) =>
              isCommitSelected(selection, d)
            );

            // Update the count display
            if (selectionCountRef.current) {
              selectionCountRef.current.textContent = `${selectedCommits.length || "No"} commits selected`;
            }

            // Only proceed if we have commits selected
            if (selectedCommits.length > 0) {
              // Highlight selected commits
              d3.selectAll(".commit-circle")
                .filter((d) => isCommitSelected(selection, d))
                .classed("selected", true)
                .attr("fill", "#ff6b6b") // Red for selected
                .style("fill-opacity", 1);

              // Generate language breakdown for selected commits
              if (languageBreakdownRef.current) {
                languageBreakdownRef.current.innerHTML = "";

                // Get all lines from selected commits
                const allSelectedLines = selectedCommits.flatMap(
                  (commit) => commit.lines
                );

                // Create language breakdown
                const languageBreakdown = d3.rollup(
                  allSelectedLines,
                  (v) => v.length,
                  (d) => d.type || "unknown"
                );

                // Convert to array and sort by count
                const filteredBreakdown = Array.from(
                  languageBreakdown.entries()
                )
                  .filter(([language]) => language && language !== "")
                  .sort(([, a], [, b]) => b - a);

                if (filteredBreakdown.length > 0) {
                  // Create container for horizontal display
                  const container = document.createElement("div");
                  container.className =
                    "language-breakdown-container flex flex-wrap gap-4 mt-2 justify-start";
                  languageBreakdownRef.current.appendChild(container);

                  // Add header as first item
                  const header = document.createElement("div");
                  header.className =
                    "language-breakdown-header self-center mr-2";
                  header.textContent = "Language Breakdown:";
                  container.appendChild(header);

                  // Calculate total for percentage
                  const totalLines = filteredBreakdown.reduce(
                    (sum, [, count]) => sum + count,
                    0
                  );

                  // Add each language as a horizontal item
                  filteredBreakdown.forEach(([language, count]) => {
                    const proportion = count / totalLines;
                    const formatted = d3.format(".1~%")(proportion);

                    const item = document.createElement("div");
                    item.className =
                      "language-item px-3 py-2 rounded-lg " +
                      (darkMode ? "bg-gray-700" : "bg-gray-100");

                    const langName = document.createElement("span");
                    langName.className = "font-medium";
                    langName.textContent = String(language).toUpperCase();

                    const langStats = document.createElement("span");
                    langStats.className = "ml-2 opacity-80";
                    langStats.textContent = `${count} (${formatted})`;

                    item.appendChild(langName);
                    item.appendChild(langStats);
                    container.appendChild(item);
                  });
                }
              }
            }
          } else {
            // No selection - reset count and clear language breakdown
            if (selectionCountRef.current) {
              selectionCountRef.current.textContent = "No commits selected";
            }
            if (languageBreakdownRef.current) {
              languageBreakdownRef.current.innerHTML = "";
            }
          }
        };

        // Load and process data
        const data = await loadData();
        dataRef.current = data;

        if (data.length === 0) {
          if (statsRef.current) {
            statsRef.current.innerHTML = `
              <div class="text-center p-8">
                <p class="text-lg ${darkMode ? "text-white" : "text-gray-800"}">No commit data available</p>
                <p class="text-sm ${darkMode ? "text-gray-400" : "text-gray-600"} mt-2">Unable to load repository commit history</p>
              </div>
            `;
          }
          return;
        }

        const commits = processCommits(data);
        commitsRef.current = commits;

        // Render basic stats
        renderCommitInfo(data, commits);

        // Set up visualization dimensions
        const margin = { top: 60, right: 120, bottom: 80, left: 80 };
        const width = Math.max(800, containerRef.current?.clientWidth || 800);
        const height = 500;

        const usableArea = {
          left: margin.left,
          right: width - margin.right,
          top: margin.top,
          bottom: height - margin.bottom,
          width: width - margin.left - margin.right,
          height: height - margin.top - margin.bottom,
        };

        // Clear and create SVG
        d3.select(chartRef.current).selectAll("*").remove();
        const svg = d3
          .select(chartRef.current)
          .append("svg")
          .attr("width", width)
          .attr("height", height);

        // Set up scales
        const [minDate, maxDate] = d3.extent(commits, (d) => d.datetime);
        xScale = d3
          .scaleTime()
          .domain([minDate, maxDate])
          .range([usableArea.left, usableArea.right])
          .nice();

        yScale = d3
          .scaleLinear()
          .domain([0, 24])
          .range([usableArea.bottom, usableArea.top]);

        const [minLines, maxLines] = d3.extent(commits, (d) => d.totalLines);
        rScale = d3.scaleSqrt().domain([minLines, maxLines]).range([3, 15]);

        // Create brush
        const brush = d3
          .brush()
          .extent([
            [usableArea.left, usableArea.top],
            [usableArea.right, usableArea.bottom],
          ])
          .on("brush end", brushed);

        // Add brush to SVG
        svg.append("g").attr("class", "brush").call(brush);

        // Add gridlines
        const gridlines = svg
          .append("g")
          .attr("class", "gridlines")
          .attr("transform", `translate(${usableArea.left}, 0)`);

        gridlines.call(
          d3
            .axisLeft(yScale)
            .tickFormat("")
            .tickSize(-usableArea.width)
            .tickValues(d3.range(0, 25, 4)) // Every 4 hours
        );

        // Add axes
        const xAxis = d3.axisBottom(xScale).tickFormat(d3.timeFormat("%b %d"));
        const yAxis = d3.axisLeft(yScale).tickFormat((d) => {
          if (d === 0) return "12 AM";
          if (d === 12) return "12 PM";
          if (d < 12) return `${d} AM`;
          return `${d - 12} PM`;
        });

        // Add X axis
        svg
          .append("g")
          .attr("transform", `translate(0, ${usableArea.bottom})`)
          .call(xAxis)
          .append("text")
          .attr("x", usableArea.left + usableArea.width / 2)
          .attr("y", 40)
          .attr("fill", darkMode ? "#e5e7eb" : "currentColor")
          .attr("text-anchor", "middle")
          .text("Date");

        // Add Y axis
        svg
          .append("g")
          .attr("transform", `translate(${usableArea.left}, 0)`)
          .call(yAxis)
          .append("text")
          .attr("transform", "rotate(-90)")
          .attr("x", -usableArea.top - usableArea.height / 2)
          .attr("y", -40)
          .attr("fill", darkMode ? "#e5e7eb" : "currentColor")
          .attr("text-anchor", "middle")
          .text("Time of Day");

        // Sort commits by size for better visibility
        const sortedCommits = d3.sort(commits, (d) => -d.totalLines);

        // Add circles for commits
        svg
          .selectAll(".commit-circle")
          .data(sortedCommits)
          .enter()
          .append("circle")
          .attr("class", "commit-circle")
          .attr("cx", (d) => xScale(d.datetime))
          .attr("cy", (d) => yScale(d.hourFrac))
          .attr("r", (d) => rScale(d.totalLines))
          .attr("fill", darkMode ? "#ffffff" : "#374151") // Single color for all dots
          .style("fill-opacity", 0.7)
          .style("stroke", darkMode ? "#6b7280" : "#9ca3af")
          .style("stroke-width", 1)
          .style("cursor", "pointer")
          .on("mouseover", function (event, d) {
            // Show tooltip
            if (tooltipRef.current) {
              updateTooltip(d);
              tooltipRef.current.hidden = false;
              const tooltip = d3.select(tooltipRef.current);
              tooltip
                .style("left", event.pageX + 10 + "px")
                .style("top", event.pageY - 10 + "px");
            }

            // Highlight circle
            d3.select(this).style("fill-opacity", 1).style("stroke-width", 2);
          })
          .on("mousemove", function (event) {
            if (tooltipRef.current) {
              const tooltip = d3.select(tooltipRef.current);
              tooltip
                .style("left", event.pageX + 10 + "px")
                .style("top", event.pageY - 10 + "px");
            }
          })
          .on("mouseout", function () {
            // Hide tooltip
            if (tooltipRef.current) {
              tooltipRef.current.hidden = true;
            }

            // Reset circle appearance (unless it's selected)
            if (!d3.select(this).classed("selected")) {
              d3.select(this)
                .style("fill-opacity", 0.7)
                .style("stroke-width", 1);
            }
          })
          .on("click", function (event, d) {
            window.open(d.url, "_blank");
          });

        // Raise dots above the brush overlay
        svg.selectAll(".commit-circle").raise();
      } catch (error) {
        console.error("Error in renderVisualization:", error);
        if (statsRef.current) {
          statsRef.current.innerHTML = `
            <div class="text-center p-8">
              <p class="text-lg ${darkMode ? "text-white" : "text-gray-800"}">Error loading visualization</p>
              <p class="text-sm ${darkMode ? "text-gray-400" : "text-gray-600"} mt-2">${error.message}</p>
            </div>
          `;
        }
      }
    };

    renderVisualization();

    // Add custom styles
    const newStyle = document.createElement("style");
    newStyle.textContent = `
      .commit-graph-container .tooltip {
        position: absolute;
        background: ${darkMode ? "rgba(31, 41, 55, 0.95)" : "rgba(255, 255, 255, 0.95)"};
        border: 1px solid ${darkMode ? "#4b5563" : "#d1d5db"};
        border-radius: 8px;
        padding: 12px;
        font-size: 14px;
        pointer-events: none;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        z-index: 1000;
        color: ${darkMode ? "#f3f4f6" : "#1f2937"};
      }
      
      .commit-graph-container .tooltip dt {
        font-weight: 600;
        margin-top: 0.5rem;
        color: ${darkMode ? "#e5e7eb" : "#374151"};
      }
      
      .commit-graph-container .tooltip dt:first-child {
        margin-top: 0;
      }
      
      .commit-graph-container .tooltip dd {
        margin-left: 0;
        margin-bottom: 0.25rem;
        color: ${darkMode ? "#d1d5db" : "#6b7280"};
      }
      
      .commit-graph-container .tooltip a {
        color: ${darkMode ? "#60a5fa" : "#3b82f6"};
        text-decoration: underline;
      }
      
      .commit-graph-container .language-breakdown-container {
        display: flex;
        flex-wrap: wrap;
        gap: 1rem;
        margin-top: 0.5rem;
        justify-content: flex-start;
        align-items: center;
      }
      
      .commit-graph-container .language-breakdown-header {
        font-weight: 600;
        color: ${darkMode ? "#e5e7eb" : "#374151"};
        margin-right: 0.5rem;
        align-self: center;
      }
      
      .commit-graph-container .language-item {
        padding: 0.5rem 0.75rem;
        border-radius: 0.5rem;
        background-color: ${darkMode ? "rgba(55, 65, 81, 0.7)" : "rgba(243, 244, 246, 0.7)"};
        font-size: 0.9rem;
        line-height: 1.2;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      
      .commit-graph-container .language-item span {
        display: block;
      }

      .commit-graph-container .gridlines line {
        stroke: ${darkMode ? "#4b5563" : "#d1d5db"};
        stroke-opacity: 0.5;
      }

      .commit-graph-container .gridlines path {
        display: none;
      }

      .commit-graph-container .brush .selection {
        fill-opacity: 0.1;
        stroke: ${darkMode ? "#60a5fa" : "#3b82f6"};
        stroke-opacity: 0.7;
        stroke-dasharray: 5 3;
      }

      .commit-graph-container circle.selected {
        stroke: #ff6b6b;
        stroke-width: 2px;
      }
    `;
    document.head.appendChild(newStyle);

    return () => {
      if (newStyle && newStyle.parentNode) {
        newStyle.parentNode.removeChild(newStyle);
      }
    };
  }, [darkMode]);

  return (
    <div
      className={`w-full mt-16 mb-16 ${
        darkMode ? "text-white" : "text-gray-800"
      }`}
      ref={containerRef}
    >
      <div className="commit-graph-container">
        <h2 className={`text-center text-3xl font-bold mb-2`}>
          Portfolio Development Activity
        </h2>
        <p className="text-center text-lg mb-8">
          Tracking commits and development patterns for this personal portfolio
        </p>

        {/* Stats bar - horizontal instead of vertical */}
        <div
          ref={statsRef}
          className={`p-6 rounded-lg mb-8 ${
            darkMode
              ? "bg-gray-800/80 border border-gray-700"
              : "bg-white/80 border border-gray-200"
          }`}
        ></div>

        {/* Main chart section - now full width */}
        <div
          className={`p-6 rounded-lg ${
            darkMode
              ? "bg-gray-800/80 border border-gray-700"
              : "bg-white/80 border border-gray-200"
          }`}
        >
          <h3 className="text-xl font-semibold mb-4">Commits by Time of Day</h3>
          <p className="mb-4 opacity-75">
            Drag to select commits and see language breakdown. Click dots to
            view commits on GitHub.
          </p>
          <div ref={chartRef}></div>

          <dl ref={tooltipRef} className="tooltip" hidden>
            <dt>Commit</dt>
            <dd>
              <a href="" id="commit-link" target="_blank" rel="noreferrer"></a>
            </dd>
            <dt>Date</dt>
            <dd id="commit-date"></dd>
            <dt>Time</dt>
            <dd id="commit-time"></dd>
            <dt>Author</dt>
            <dd id="commit-author"></dd>
            <dt>Lines</dt>
            <dd id="commit-lines"></dd>
          </dl>

          <div className="selection-info mt-4">
            <p ref={selectionCountRef} id="selection-count">
              No commits selected
            </p>
            <dl ref={languageBreakdownRef} className="stats mt-2"></dl>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CommitGraph;
